### ISSUE TITLE
Join the Slack here! (chat)

### ISSUE THREAD

**Issue by quentinguidee** [Omega-Numworks/Online-Installer#5]
https://join.slack.com/t/omeganumworks/shared_invite/enQtODI0NjU5NDU2MDUwLTRkODc1NDgzNmJkMzNlZGEyYWU2YzNlOWY4NWZlZjk1ZTM0YzY0ZjJjYTgyYzYwNDA1ZWZiYmUyMjA2MGU0ZDM

**Comment by LeGmask** [comment]
The link doesn't work :-(

**Comment by quentinguidee** [comment]
@LeGmask Oops, thanks for this comment, it's fixed ;)
